### ISSUE TITLE
Failed to activate the multiple-cursors-clipboard package

### ISSUE THREAD

**Issue by mferroni** [abe33/atom-multiple-cursors-clipboard#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.2
**Thrown From**: [multiple-cursors-clipboard](https://github.com/abe33/atom-multiple-cursors-clipboard) package, v0.1.1
### Stack Trace

Failed to activate the multiple-cursors-clipboard package

```
At Cannot find module '/Applications/Atom.app/Contents/Resources/app/src/editor'

Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/src/editor'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.activate (/Users/marcoferroni/.atom/packages/multiple-cursors-clipboard/lib/multiple-cursors-clipboard.coffee:9:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -5:57.5 editor:consolidate-selections (atom-text-editor.editor)
  2x -5:55.6 core:select-down (atom-text-editor.editor)
     -5:53.7 core:move-up (atom-text-editor.editor)
     -5:53.4 core:move-down (atom-text-editor.editor)
  3x -5:53.1 editor:add-selection-below (atom-text-editor.editor)
  2x -5:52.0 core:move-right (atom-text-editor.editor)
     -5:51.0 editor:consolidate-selections (atom-text-editor.editor)
     -2:18.3 editor:select-to-beginning-of-word (atom-text-editor.editor)
     -2:17.6 clipboard-history:copy (atom-text-editor.editor)
  6x -2:17.3 core:paste (atom-text-editor.editor)
  3x -2:15.2 core:undo (atom-text-editor.editor)
     -2:13.7 clipboard-history:copy (atom-text-editor.editor)
     -2:13.3 core:paste (atom-text-editor.editor)
     -2:12.7 core:undo (atom-text-editor.editor)
     -0:12.9 core:paste (atom-text-editor.editor.mini)
     -0:12.5 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "seti-ui",
      "succulent"
    ],
    "projectHome": "/Users/marcoferroni/Documents/www/aliveshoes_main",
    "disabledPackages": [
      "vim-mode"
    ],
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.log",
      "*~.nib",
      "*.png",
      "*.jpg",
      "*.gif",
      "*.jpeg",
      "*.svg"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-textmate, v0.0.1
clipboard-history, v0.6.4
git-diff-details, v0.11.0
language-haml, v0.19.0
multiple-cursors-clipboard, v0.1.1
ruby-define-method, v0.2.0
seti-ui, v0.6.3
succulent, v0.1.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
This package is no longer maintained since Atom 0.95 as its functionality was added into core since then. It was a temporary solution while waiting for my PR to make it into core. 
This is explained in the README.
